### ISSUE TITLE
Avatar not appearing?

### ISSUE THREAD

**Issue by sa7mon** [caseyscarborough/github-activity#16]
For some reason, my GitHub icon isn't appearing in the HTML output. I tried sticking my user name into the demo: http://caseyscarborough.com/github-activity/ and still got the same problem. When I check my public activity, though, it does show up: https://github.com/sa7mon?tab=activity

Do I need to set something else in git config?

**Comment by caseyscarborough** [comment]
This is mainly due to the inability to get someone's avatar URL from the payload received from the GitHub API. The payload for an event from the API has a "commits" section in the following format:

```json
"commits":[  
  {  
     "sha":"c610bac0bdaef166cf0ff52ac41a86ffc7af2509",
     "author":{  
        "email":"user@example.com",
        "name":"Example User"
     },
     "message":"This is the commit message.",
     "distinct":true,
     "url":"https://api.github.com/repos/user/example/commits/c610bac0bdaef166cf0ff52ac41a86ffc7af2509"
  }
]
```

I started this library when GitHub solely used Gravatar for user avatars, so to remedy this I made it so that image displayed would be the Gravatar for the email address of the commit. In your case, it doesn't look like you have a Gravatar for your git configured email address, which is causing the missing images. Setting an image for this would cause yours to appear.

There may be another way to get the image without making extra requests to the API, but I haven't discovered it.
