### ISSUE TITLE
github-activity not working

### ISSUE THREAD

**Issue by JMatharu** [caseyscarborough/github-activity#17]
I am always getting 

"User jmatharu wasn't found."

Any issue going around???

Try searching here as well - http://caseyscarborough.com/github-activity/

**Comment by caseyscarborough** [comment]
Are you hosting your own JS file? See [this issue](https://github.com/caseyscarborough/github-activity/issues/8). It happens due to GitHub's rate limit when not authenticated.

You can get around the rate limit by creating a GitHub application and passing your client ID and client secret as parameters like so:

```js
GitHubActivity.feed({
    username: "jmatharu",
    selector: "#feed",
    clientId: "CLIENT_ID",
    clientSecret: "CLIENT_SECRET"
});
```

**Comment by LukeFarnell** [comment]
@caseyscarborough putting the clientid and secret in the code is a bad idea... This is a huge security concern and anyone could use the id and secret to post on behalf of the user

**Comment by caseyscarborough** [comment]
@LukeFarnell For most use cases, people will not need to do this. But GitHub's API limits unauthenticated requests to 60 per hour. If you require more than this, you'll need to authenticate.

**Comment by caseyscarborough** [comment]
Closing this issue for now.
